const mongoose = require("mongoose");

module.exports = mongoose.model('Blogs', {
    title: { type: String },
    category: { type: String },
    subtitle: { type: String },
    tagline: { type: String },
    authorName: { type: String },
    authorAvatar: { type: String },
    location: { type: String },
    eventDates: { type: String },
    createdAt: { type: String },
    description: { type: String },
    descriptions01: { type: String },
    descriptions02: { type: String },
    descriptions03: { type: String },
    heading1: { type: String },
    description1: { type: String },
    heading2: { type: String },
    description2: { type: String },
    heading3: { type: String },
    description3: { type: String },
    heading4: { type: String },
    description4: { type: String },
    heading5: { type: String },
    description5: { type: String },
    point1: { type: String },
    point2: { type: String },
    blogImage: { type: String }
}, 'blogs')
