const mongoose = require("mongoose");

module.exports = mongoose.model('Conferences', {
    title: { type: String },
    subTitle: { type: String },
    startDate: { type: String },
    endDate: { type: String },
    country: { type: String },
    venue: { type: String },
    focus: { type: String },
    details: { type: String },
    discountHeading: { type: String },
    discount: { type: String },
    description_0: { type: String },
    description_1: { type: String },
    description_2: { type: String },
    categoryHeading: { type: String },
    category: { type: String },
    category1: { type: String },
    category2: { type: String },
    registrationName1: { type: String },
    registrationName2: { type: String },
    registrationName3: { type: String },
    registrationType1: { type: String },
    registrationType2: { type: String },
    registrationType3: { type: String },
    registrationType4: { type: String },
    registrationType5: { type: String },
    registrationType6: { type: String },
    registrationType7: { type: String },
    registrationType8: { type: String },
    registrationType9: { type: String },
    taxDetails: { type: String },
    note: { type: String },
    conferenceImage: { type: String, },
    conferenceImages: { type: [String], default: [] }
}, 'conferences')